# Generated by Django 4.2.21 on 2025-06-09 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('player_age', models.IntegerField(blank=True, null=True)),
                ('player_career', models.IntegerField(blank=True, null=True)),
                ('player_titles', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team_no', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=20)),
                ('games', models.IntegerField(blank=True, null=True)),
                ('hands', models.IntegerField(blank=True, null=True)),
                ('points', models.FloatField(blank=True, null=True)),
                ('first_place', models.IntegerField(blank=True, null=True)),
                ('second_place', models.IntegerField(blank=True, null=True)),
                ('third_place', models.IntegerField(blank=True, null=True)),
                ('last_place', models.IntegerField(blank=True, null=True)),
                ('high_score', models.IntegerField(blank=True, null=True)),
                ('average_score', models.FloatField(blank=True, null=True)),
                ('average_score_lost', models.FloatField(blank=True, null=True)),
                ('mangan_or_higher_rate', models.FloatField(blank=True, null=True)),
                ('win_hand_rate', models.FloatField(blank=True, null=True)),
                ('dealin_rate', models.FloatField(blank=True, null=True)),
                ('riichi_declaration_rate', models.FloatField(blank=True, null=True)),
                ('call_rate', models.FloatField(blank=True, null=True)),
                ('tenpai_rate_at_exhaustive_draw', models.FloatField(blank=True, null=True)),
                ('tenpai_bounus_net_gain_at_draw', models.FloatField(blank=True, null=True)),
                ('draw_rate', models.FloatField(blank=True, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MPrediction.membership')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('player_no', models.IntegerField(unique=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MPrediction.team')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MPrediction.player'),
        ),
        migrations.AddField(
            model_name='membership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MPrediction.team'),
        ),
    ]
