# Generated by Django 4.2.20 on 2025-04-27 14:01

import ImageTranscription.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageTranscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdfs/', validators=[ImageTranscription.models.validate_pdf])),
            ],
        ),
    ]
